//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_new1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TablememberDs1101605
    {
        [Required(ErrorMessage = "請輸入編號")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "只能輸入數字")]
        public int mId { get; set; }
        [Required(ErrorMessage = "請輸入名稱")]
        public string mName { get; set; }
        [Required(ErrorMessage = "請輸入年紀")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "只能輸入數字")]
        public int age { get; set; }
        [Required(ErrorMessage = "請輸入身高")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "只能輸入數字")]
        public double height { get; set; }
        [Required(ErrorMessage = "請輸入體重")]
        public double weight { get; set; }
        [Required(ErrorMessage = "請輸入Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        [Required(ErrorMessage = "請輸入球齡")]
        public int ballage { get; set; }
        [Required(ErrorMessage = "請輸入隊伍編號")]
        public int tId { get; set; }
    }
}
